spring:
  application:
    name: project-bank
  cloud:
    config:
      uri: http://localhost:8081
      username: prueba
      password: Pru3b4
  data:
    mongodb:
      database: bank
      host: localhost
      port: 27017
server:
  port: 8090
management:
  security:
    enable: false
security:
  basic:
    enable: false
