package com.project.bank.ProjectBank.Utils;

public class UIUtils {
  public static final String BASEURL = "/customer";
  public static final String BASEURLACCOUNTTYPE = "/account-type";
  public static final String CUSTOMER_ALL = "/find-all";
  public static final String CUSTOMER_ID = "/find-id/{customerId}";
  public static final String CUSTOMER_INS = "save";
  public static final String CUSTOMER_UPD = "update";
  public static final String CUSTOMER_DEL = "delete/{customerId}";
  public static final String BANKPRODUCT_BASEURL = "productbank";
  public static final String BANKPRODUCT_INS = "save";
  public static final String BANKPRODUCT_UPD = "update";
  public static final String BANKPRODUCT_DEL = "delete/{bankProductId}";
  public static final String BANKPRODUCT_ALL = "find-all";
  public static final String BANKPRODUCT_ID = "find-id/{bankProductId}";
  public static final String CUSTOMERTYPE_BASEURL = "customertype";
  public static final String CUSTOMERTYPE_INS = "save";
  public static final String CUSTOMERTYPE_UPD = "update";
  public static final String CUSTOMERTYPE_DEL = "delete/{customerTypeId}";
  public static final String CUSTOMERTYPE_ALL = "find-all";
  public static final String CUSTOMERTYPE_ID = "find-id/{customerTypeId}";
  public static final String ACCOUNT_TYPE_ALL = "/find-all";
  public static final String ACCOUNT_TYPE_ID = "/find-id/{idAccountType}";
  public static final String ACCOUNT_TYPE_INS = "save";
  public static final String ACCOUNT_TYPE_UPD = "update";
  public static final String ACCOUNT_TYPE_DEL = "delete/{id}";
  public static final String BASEURL_TRANSACTION = "/transaction";
  public static final String TRANSACTION_ALL = "/find-all";
  public static final String TRANSACTION_ID = "/find-id/{id}";
  public static final String TRANSACTION_INS = "save";
  public static final String TRANSACTION_UPD = "update";
  public static final String TRANSACTION_DEL = "delete/{id}";
  public static final String TRANSACTION_BALANCE = "balance/{id}";
  public static final String TRANSACTION_PAY_CREDIT = "pay-credit";
  public static final String BASEURL_CARD = "/card";
  public static final String CARD_CREATE = "/card-create";
    public static final String CARD_PAY_BALANCE="/pay-balance";
  public static final String CARD_DEBIT_CREDIT="/debit-credit";
  public static final String CARD_BALANCE_BY_ID="/card-balance/{id}";
  public static final String CARD_BALANCE_ALL="/balance-all";
  public static final String CARD_LOAD_BALANCE="/load-balance/{id}";
}